update volunerablity

diff --git a/.github/workflows/dokcer-library.yaml b/.github/workflows/dokcer-library.yaml
--- a/.github/workflows/dokcer-library.yaml
+++ b/.github/workflows/dokcer-library.yaml
@@ -103,16 +103,38 @@ jobs:
           ecr_repo_name=$(yq eval '.ecr_repo_name' "$CONFIG_FILE")
           docker_image_tag=$(yq eval '.docker_image_tag' "$CONFIG_FILE")
           account_name=$(yq eval '.account_name' "$CONFIG_FILE")
+          skip_vulnerability_check=$(yq eval '.skip_vulnerability_check // "false"' "$CONFIG_FILE" | tr '[:upper:]' '[:lower:]')
 
           echo "ecr_repo_name=$ecr_repo_name" >> $GITHUB_ENV
           echo "docker_image_tag=$docker_image_tag" >> $GITHUB_ENV
+          echo "skip_vulnerability_check=$skip_vulnerability_check" >> $GITHUB_ENV
           echo "account_name=$account_name" >> $GITHUB_ENV
-
       - name: Run Trivy Vulnerability Scan
         run: |
           IMAGE_TAG="$account_name/$ecr_repo_name:$docker_image_tag"
           echo "🔍 Running Trivy scan on $IMAGE_TAG..."
-          trivy image --format table --exit-code 1 --ignore-unfixed --pkg-types os,library --severity HIGH,CRITICAL "$IMAGE_TAG" | tee trivy-results-${{ env.docker_image_tag }}.txt
+          trivy image --format table --ignore-unfixed --pkg-types os,library --severity HIGH,CRITICAL "$IMAGE_TAG" | tee trivy-results-${{ env.docker_image_tag }}.txt
+          VULN_COUNT=$(trivy image --format json --ignore-unfixed --pkg-types os,library --severity HIGH,CRITICAL "$IMAGE_TAG" | jq '[.Results[].Vulnerabilities[]? | select(.Severity=="HIGH" or .Severity=="CRITICAL")] | length')
+          echo "🛑 Detected HIGH/CRITICAL vulnerabilities: $VULN_COUNT"
+          if [[ "${{ env.skip_vulnerability_check }}" == "true" ]]; then
+            echo "⚠️ Skipping vulnerability enforcement as per user input."
+          else
+            if [[ "$VULN_COUNT" -gt 0 ]]; then
+              echo "❌ Vulnerabilities found. Failing the job."
+              exit 1
+            else
+              echo "✅ No HIGH/CRITICAL vulnerabilities found. Proceeding."
+            fi
+          fi
+  # env:
+  #   skip_vulnerability_check: "no" # Default to "no", user can override
+    
+
+      # - name: Run Trivy Vulnerability Scan
+      #   run: |
+      #     IMAGE_TAG="$account_name/$ecr_repo_name:$docker_image_tag"
+      #     echo "🔍 Running Trivy scan on $IMAGE_TAG..."
+      #     trivy image --format table --exit-code 1 --ignore-unfixed --pkg-types os,library --severity HIGH,CRITICAL "$IMAGE_TAG" | tee trivy-results-${{ env.docker_image_tag }}.txt
 
   # push:
   #   needs: scan
